query QueryComingEvents(
  $first: Int = 99,
) {
  comingEvents(
    first:$first,
    where: {
      language: EN #只接英文版
    }
  ) {
    nodes {
      slug
      date
      title
      content(format: RENDERED)
      comingEventCustomFields {
        subtitle
        scheduleDate
        contactTitle
        contactNumber
        contactEmail
        relatedHulls {
          yachtSlug
          hullName
        }
        showInfoTable {
          dateAndTimeRows {
            dateAndTimes
          }
          dockNumber
        }
      }
    }
  }
}

query QueryYachtHull($yachtSlug: ID!, $language: LanguageCodeEnum!) {
  yacht(id: $yachtSlug, idType: SLUG) {
    translation(language: $language) {
      slug
      title
      yachtCustomFields {
        hulls {
          hullName
          exteriorImages {
            image {
              node {
                mediaItemUrl
                srcSet
                placeholder: sourceUrl(size: VMO_32)
              }
            }
          }
        }
      }
    }
  }
}