query QueryComingEvents(
  $first: Int = 99,
) {
  comingEvents(
    first:$first,
    where: {
      language: EN #只接英文版
    }
  ) {
    nodes {
      slug
      date
      title
      content(format: RENDERED)
      comingEventCustomFields {
        subtitle
        scheduleDate
        contactTitle
        contactNumber
        contactEmail
        relatedHulls {
          yachtSlug
          hullName
        }
        showInfoTable {
          dateAndTimeRows {
            dateAndTimes
          }
          dockNumber
        }
      }
    }
  }
}