#import '../fragments/yacht.gql'

query QueryCommonData(
  $language: LanguageCodeFilterEnum,
  $translation: LanguageCodeEnum!
){
  globalSettings(
    language: $language
  ) {
    mainMenu {
      menuItemImages {
        normal {
          image {
            node {
              mediaItemUrl
            }
          }
          video {
            node {
              mediaItemUrl
            }
          }
        }
        about {
          image {
            node {
              mediaItemUrl
            }
          }
          video {
            node {
              mediaItemUrl
            }
          }
        }
        models {
          image {
            node {
              mediaItemUrl
            }
          }
          video {
            node {
              mediaItemUrl
            }
          }
        }
      }
      series {
        series {
          nodes {
            ... on YachtSeries {
              translation(language: $translation) {
                slug
                name
                yachtsSeriesCustomFields {
                  seriesSimpleDescription
                }
              }
            }
          }
        }
        image {
          node {
            mediaItemUrl
          }
        }
        video {
          node {
            mediaItemUrl
          }
        }
        yachts {
          yacht {
            nodes {
              ... on Yacht {
                translation(language: $translation) {
                  ...yachtBasic
                  yachtCustomFields {
                    ...yachtSpecsTable
                  }
                }
              }
            }
          }
          image {
            node {
              mediaItemUrl
            }
          }
          video {
            node {
              mediaItemUrl
            }
          }
        }
      }
    }
    externalLinks {
      career
      socialMedia {
        facebook
        instagram
        linkedin
        twitter
        youtube
      }
    }
  }
  yachtSeriesList(
    first: 99,
    where: {
      language: $language,
      orderby: TERM_ORDER,
      order: ASC,
    }
  ) {
    nodes {
      slug
      name
      description
      yachtsSeriesCustomFields {
        seriesSimpleDescription
        seriesKeyImage {
          node {
            mediaItemUrl
          }
        }
      }
    }
  }
}