#import '../fragments/post.gql'

query QueryNews(
  $first: Int
  $last: Int
  $after: String
  $before: String
  $relatedYachtSeries: String
  $categories: [String]
  $year: Int
  $categoriesOperator: TaxQueryOperator = NOT_IN
  $language: LanguageCodeFilterEnum
) {
  posts(
    first: $first
 		last: $last,
    after: $after,
    before: $before,
    where: {
      language: $language
      dateQuery: {
        year: $year
      }
      taxQuery: {
        relation: AND,
        taxArray: [
          {
            taxonomy: CATEGORY,
            field: SLUG,
            terms: ["uncategorized", "cover-story", "events"]
            operator: NOT_IN,
          },
          {
            taxonomy: CATEGORY,
            field: SLUG,
            terms: $categories,
            operator: $categoriesOperator,
          }
        ]
      }
      relatedYachtSeries: $relatedYachtSeries
    }
  ) {
    nodes {
      ...postBasic
      categories {
        nodes {
          slug
          name
          parentId
        }
      }
      postCustomFields {
        ...postCoverImage
        ...postGallery
        ...postRelatedYachts
      }
    }
    pageInfo {
      endCursor
      hasNextPage
      hasPreviousPage
      startCursor
    }
  }
}