query QuerySinglePublication($slug:ID!) {
  publication(id: $slug, idType:SLUG) {
    title
    slug
    publicationCustomFields {
      publication {
        publicationCover {
          node {
            mediaItemUrl
            srcSet
          }
        }
        pdf {
          node {
            mediaItemUrl
          }
        }
      }
    }
  }
}