query QuerySinglePublication($slug:ID!) {
  publication(id: $slug, idType:SLUG) {
    title
    slug
    publicationCustomFields {
      relatedYachts {
        seriesSlug
      }
      album {
        image {
          node {
            mediaItemUrl
          }
        }
      }
    }
  }
}