#import '../fragments/yacht.gql'

query QueryMenu($slug:ID!) {
  yachtSeries(id: $slug, idType: SLUG) {
    yachts(first: 99) {
      nodes {
        ...yachtBasic
        yachtCustomFields {
          ...yachtSpecsTable
        }
      }
    }
  }
}