query QueryMilestone {
  aboutHorizon {
    aboutHorizonCustomFields {
      milestone {
        year
        title
        description
        image {
          node {
            mediaItemUrl
          }
        }
      }
    }
  }
}