query QueryMilestone(
  $language: LanguageCodeFilterEnum
) {
  aboutHorizon(
    language: $language
  ) {
    aboutHorizonCustomFields {
      milestone {
        year
        title
        description
        image {
          node {
            mediaItemUrl
            srcSet
          }
        }
      }
    }
  }
}