query QueryTranslations(
  $language: LanguageCodeFilterEnum,
) {
  translationSettings(language: $language) {
    translationFields {
      translations {
        key
        value
      }
    }
  }
}