query QueryPageAboutInnovation(
  $language: LanguageCodeFilterEnum
) {
  aboutInnovation(
    language: $language
  ) {
    aboutInnovationCustomFields {
      featuredVideo {
        node {
          mediaItemUrl
        }
      }
      contentList {
        basic {
          title
          description
          keyImage {
            node {
              mediaItemUrl
              srcSet
            }
          }
        }
        content(sizesString: "(max-width: 991px) 100vw, 900px")
      }
    }
  }
}