query QueryPageAboutTheGroup(
  $language: LanguageCodeFilterEnum
) {
  aboutTheGroup(
    language: $language
  ) {
    aboutTheGroupCustomFields {
      atgpHeroImage {
        node {
          mediaItemUrl
          srcSet
        }
      }
      atgpGroupIntroduction
      atgpOrganization {
        companies {
          basic {
            componyName
            subtitle
            since
          }
          shortDescription
          description
          images {
            grid {
              node {
                mediaItemUrl
                srcSet
              }
            }
            banner {
              node {
                mediaItemUrl
                srcSet
              }
            }
          }
          numericalData {
            prefix
            number
            unit
          }
        }
      }
    }
  }
}