query QueryPageAboutDesignAndCraft(
  $language: LanguageCodeFilterEnum
){
  aboutDesignAndCraft(
    language: $language
  ) {
    aboutDesignCustomFields {
      featuredVideo {
        node {
          mediaItemUrl
        }
      }
      contentList {
        basic {
          title
          description
          keyImage {
            node {
              mediaItemUrl
              srcSet
            }
          }
        }
        content(sizesString: "(max-width: 991px) 100vw, 900px")
        designPartnersTitle
        designPartners {
          title
          subtitle
          description
          image {
            node {
              mediaItemUrl
              srcSet
            }
          }
        }
      }
    }
  }
}