query QueryPageAboutInnovation {
  aboutInnovation {
    aboutInnovationCustomFields {
      featuredVideo {
        node {
          mediaItemUrl
        }
      }
      contentList {
        basic {
          title
          description
          keyImage {
            node {
              mediaItemUrl
            }
          }
        }
        content
      }
    }
  }
}