query QueryPageAboutInnovation(
  $language: LanguageCodeFilterEnum = EN
) {
  aboutInnovation(
    language: $language
  ) {
    aboutInnovationCustomFields {
      featuredVideo {
        node {
          mediaItemUrl
        }
      }
      contentList {
        basic {
          title
          description
          keyImage {
            node {
              mediaItemUrl
            }
          }
        }
        content
      }
    }
  }
}