query QueryPageAboutHorizon(
  $language: LanguageCodeFilterEnum = EN
) {
  aboutHorizon(
    language: $language
  ) {
    aboutHorizonCustomFields {
      firstScreen {
        backgroundVideo {
          node {
            mediaItemUrl
          }
        }
        heroImage {
          node {
            mediaItemUrl
          }
        }
        description
      }
      discoverHorizon
      imageAfterDiscoverHorizon {
        node {
          mediaItemUrl
        }
      }
      numericalData {
        yachtsBuild
        overSqftArea
        iso9001Certified
        employees
      }
      achievement {
        image {
          node {
            mediaItemUrl
          }
        }
      }
      history
    }
  }
}