query QueryPageAboutDesignAndCraft(
  $language: LanguageCodeFilterEnum = EN
){
  aboutDesignAndCraft(
    language: $language
  ) {
    aboutDesignCustomFields {
      featuredVideo {
        node {
          mediaItemUrl
        }
      }
      contentList {
        basic {
          title
          description
          keyImage {
            node {
              mediaItemUrl
            }
          }
        }
        content
        designPartnersTitle
        designPartners {
          title
          subtitle
          description
          image {
            node {
              mediaItemUrl
            }
          }
        }
      }
    }
  }
}