query QueryBrokeragePage(
  $first: Int
  $language: LanguageCodeFilterEnum
) {
  settings:brokerageSettings(
    language: $language
  ) {
    customFields:brokerageSettingCustomFields {
      lengthOptions:brokerageLengthOptions {
        label
        minValue
        maxValue
      }
    }
  }
  yachtYears(
    postType: "brokerage",
    language: $language
  )
  posts:brokerages(
    first: $first,
    where: {
      language: $language
      orderby: {
        field: MENU_ORDER,
        order: ASC,
      },
    }
  ) {
    nodes {
      slug
      title
      customFields:brokerageCustomFields {
        year
        displayPrice
        exteriorImages {
          image {
            node {
              mediaItemUrl
              srcSet
            }
          }
        }
        specTerms {
          loa {
            metric
            imperial
          }
          beam {
            metric
            imperial
          }
          engines {
            metric
            imperial
          }
        }
      }
      yachtConditions {
        nodes {
          slug
          name
        }
      }
    }
    pageInfo {
      endCursor
      hasNextPage
      hasPreviousPage
      startCursor
    }
  }
  yachtConditions(
    first: 99,
    where: {
      language: $language
    }
  ) {
    nodes {
      slug
      name
    }
  }
}

query QueryBrokerages(
  $first: Int
  $after: String
  $yachtConditions: [String]
  $yachtConditionsOperator: TaxQueryOperator = NOT_IN
  $yachtYear: String = ""
  $yachtLengthRange: String = ""
  $customOrderby: String = ""
  $language: LanguageCodeFilterEnum
) {
  posts:brokerages(
    first: $first,
    after: $after,
    where: {
      language: $language,
      orderby: {
        field: MENU_ORDER,
        order: ASC,
      },
      taxQuery: {
        relation: AND,
        taxArray: {
          taxonomy: YACHTCONDITION,
          field: SLUG,
          terms: $yachtConditions,
          operator: $yachtConditionsOperator
        }
      }
      yachtYear: $yachtYear,
      yachtLengthRange: $yachtLengthRange,
      customOrderby: $customOrderby,
    }
  ) {
    nodes {
      slug
      title
      customFields:brokerageCustomFields {
        year
        displayPrice
        exteriorImages {
          image {
            node {
              mediaItemUrl
              srcSet
            }
          }
        }
        specTerms {
          loa {
            metric
            imperial
          }
          beam {
            metric
            imperial
          }
          engines {
            metric
            imperial
          }
        }
      }
      yachtConditions {
        nodes {
          slug
          name
        }
      }
    }
    pageInfo {
      endCursor
      hasNextPage
      hasPreviousPage
      startCursor
    }
  }
}