query QueryBrokeragePage(
  $first: Int
) {
  settings:brokerageSettings {
    customFields:brokerageSettingCustomFields {
      priceCurrency:brokeragePriceCurrency
      lengthOptions:brokerageLengthOptions {
        label
        minValue
        maxValue
      }
      priceOptions:brokeragePriceOptions {
        label
        minValue
        maxValue
      }
    }
  }
  yachtYears(postType: "brokerage")
  posts:brokerages(
    first: $first,
    where: {
      orderby: {
        field: MENU_ORDER,
        order: ASC,
      },
    }
  ) {
    nodes {
      slug
      title
      customFields:brokerageCustomFields {
        year
        price
        exteriorImages {
          image {
            node {
              mediaItemUrl
            }
          }
        }
        specTerms {
          loa {
            metric
            imperial
          }
          beam {
            metric
            imperial
          }
          engines {
            metric
            imperial
          }
        }
      }
      yachtConditions {
        nodes {
          slug
          name
        }
      }
    }
    pageInfo {
      endCursor
      hasNextPage
      hasPreviousPage
      startCursor
    }
  }
  yachtConditions(first: 99) {
    nodes {
      slug
      name
    }
  }
}

query QueryBrokerages(
  $first: Int
  $after: String
  $yachtConditions: [String]
  $yachtConditionsOperator: TaxQueryOperator = NOT_IN
  $yachtYear: String = ""
  $yachtPriceRange: String = "",
  $yachtLengthRange: String = "",
  $customOrderby: String = "",
) {
  posts:brokerages(
    first: $first,
    after: $after,
    where: {
      orderby: {
        field: MENU_ORDER,
        order: ASC,
      },
      taxQuery: {
        relation: AND,
        taxArray: {
          taxonomy: YACHTCONDITION,
          field: SLUG,
          terms: $yachtConditions,
          operator: $yachtConditionsOperator
        }
      }
      yachtYear: $yachtYear,
      yachtLengthRange: $yachtLengthRange,
      yachtPriceRange: $yachtPriceRange,
      customOrderby: $customOrderby,
    }
  ) {
    nodes {
      slug
      title
      customFields:brokerageCustomFields {
        year
        price
        exteriorImages {
          image {
            node {
              mediaItemUrl
            }
          }
        }
        specTerms {
          loa {
            metric
            imperial
          }
          beam {
            metric
            imperial
          }
          engines {
            metric
            imperial
          }
        }
      }
      yachtConditions {
        nodes {
          slug
          name
        }
      }
    }
    pageInfo {
      endCursor
      hasNextPage
      hasPreviousPage
      startCursor
    }
  }
}