query QuerySingleBrokerage(
  $slug: ID!
) {
  settings:brokerageSettings {
    customFields:brokerageSettingCustomFields {
      priceCurrency:brokeragePriceCurrency
    }
  }
  post:brokerage(
    id: $slug
    idType: SLUG
  ) {
    title
    customFields:brokerageCustomFields {
      year
      price
      yachtDescription
      relatedPublicationSlug
      heroImage {
        node {
          mediaItemUrl
        }
      }
      exteriorImages {
        image {
          node {
            mediaItemUrl
          }
        }
      }
      interiorImages {
        description
        image {
          node {
            mediaItemUrl
          }
        }
      }
      featuresTable {
        tableType
        terms {
          termName
          termValue
        }
      }
      specTerms {
          loa {
            metric
            imperial
          }
          lwl {
            metric
            imperial
          }
          beam {
            metric
            imperial
          }
          draft {
            metric
            imperial
          }
          engines {
            metric
            imperial
          }
          generator {
            metric
            imperial
          }
          displacement {
            metric
            imperial
          }
          fuelCapacity {
            metric
            imperial
          }
          waterCapacity {
            metric
            imperial
          }
          cabins {
            metric
            imperial
          }
      }
    }
    yachtConditions {
      nodes {
        slug
        name
      }
    }
  }
}