query QueryCharterPage(
  $first: Int
  $language: LanguageCodeFilterEnum
) {
  settings:charterSettings(
    language: $language
  ) {
    customFields:charterSettingCustomFields {
      lengthOptions:charterLengthOptions {
        label
        minValue
        maxValue
      },
      yachtConditionSettings {
        dropdownTitle
      }
    }
  }
  yachtYears(
    postType: "charter",
    language: $language
  )
  posts:charters(
    first: $first,
    where: {
      language: $language
      orderby: {
        field: MENU_ORDER,
        order: ASC,
      },
    }
  ) {
    nodes {
      slug
      title
      customFields:charterCustomFields {
        year
        displayPrice
        exteriorImages {
          image {
            node {
              mediaItemUrl
              srcSet
            }
          }
        }
        specTerms {
          loa {
            metric
            imperial
          }
          beam {
            metric
            imperial
          }
          engines {
            metric
            imperial
          }
        }
      }
      yachtConditions:yachtConditionsCharter {
        nodes {
          slug
          name
        }
      }
    }
    pageInfo {
      endCursor
      hasNextPage
      hasPreviousPage
      startCursor
    }
  }
  yachtConditions:yachtConditionsCharter(
    first: 99,
    where: {
      language: $language
    }
  ) {
    nodes {
      slug
      name
    }
  }
}

query QueryCharters(
  $first: Int
  $after: String
  $yachtConditions: [String]
  $yachtConditionsOperator: TaxQueryOperator = NOT_IN
  $yachtYear: String = ""
  $yachtLengthRange: String = "",
  $customOrderby: String = ""
  $language: LanguageCodeFilterEnum
) {
  posts:charters(
    first: $first,
    after: $after,
    where: {
      language: $language,
      orderby: {
        field: MENU_ORDER,
        order: ASC,
      },
      taxQuery: {
        relation: AND,
        taxArray: {
          taxonomy: YACHTCONDITIONCHARTER,
          field: SLUG,
          terms: $yachtConditions,
          operator: $yachtConditionsOperator
        }
      }
      yachtYear: $yachtYear,
      yachtLengthRange: $yachtLengthRange,
      customOrderby: $customOrderby,
    }
  ) {
    nodes {
      slug
      title
      customFields:charterCustomFields {
        year
        displayPrice
        exteriorImages {
          image {
            node {
              mediaItemUrl
              srcSet
            }
          }
        }
        specTerms {
          loa {
            metric
            imperial
          }
          beam {
            metric
            imperial
          }
          engines {
            metric
            imperial
          }
        }
      }
      yachtConditions:yachtConditionsCharter {
        nodes {
          slug
          name
        }
      }
    }
    pageInfo {
      endCursor
      hasNextPage
      hasPreviousPage
      startCursor
    }
  }
}