query QuerySingleCharter(
  $slug: ID!
  $translation: LanguageCodeEnum!
) {
  post:charter(
    id: $slug
    idType: SLUG
  ) {
    translation(language: $translation){
      title
      customFields:charterCustomFields {
        year
        displayPrice
        yachtDescription
        relatedPublication {
          nodes {
            ... on Publication {
              title
              publicationCustomFields {
                publication {
                  publicationCover {
                    node {
                      mediaItemUrl
                    }
                  }
                  pdf {
                    node {
                      mediaItemUrl
                    }
                  }
                }
              }
            }
          }
        }
        heroImage {
          node {
            mediaItemUrl
          }
        }
        exteriorImages {
          image {
            node {
              mediaItemUrl
            }
          }
        }
        interiorImages {
          description
          image {
            node {
              mediaItemUrl
            }
          }
        }
        featuresTable {
          tableType
          terms {
            termName
            termValue
          }
        }
        pricingToysTable {
          tableType
          terms {
            termName
            termValue
          }
        }
        specTerms {
            loa {
              metric
              imperial
            }
            lwl {
              metric
              imperial
            }
            beam {
              metric
              imperial
            }
            draft {
              metric
              imperial
            }
            engines {
              metric
              imperial
            }
            generator {
              metric
              imperial
            }
            displacement {
              metric
              imperial
            }
            fuelCapacity {
              metric
              imperial
            }
            waterCapacity {
              metric
              imperial
            }
            cabins {
              metric
              imperial
            }
        }
      }
      yachtConditions {
        nodes {
          translation(language: $translation){
            slug
            name
          }
        }
      }
    }
  }
}