query QueryHomePage {
  homePageSettings {
    homePageCustomFields{
      homePageKeyVision {
        mainTitle
        heroImage {
          node {
            mediaItemUrl
          }
        }
        heroVideo {
          node {
            mediaItemUrl
          }
        }
      }
      homePageIntroduction {
        smallVideo {
          node {
            mediaItemUrl
          }
        }
        innovationVideo {
          node {
            mediaItemUrl
          }
        }
      }
    }
  }

  posts(
    first: 3
    where: {
      taxQuery: {
        relation: AND,
        taxArray: [
          {
            taxonomy: CATEGORY,
            field: SLUG,
            terms: ["uncategorized", "events"]
            operator: NOT_IN,
          },
        ]
      }
    }
  ) {
    nodes {
      slug
      title
      date
      categories {
        nodes {
          slug
          name
        }
      }
      postCustomFields {
        gallery {
          image {
            node {
              mediaItemUrl
            }
          }
        }
      }
    }
  }
}