query QueryInvestorPage(
  $first: Int
  $after: String
  $language: LanguageCodeFilterEnum
  $translation: LanguageCodeEnum!
) {
  posts:investors(
    first: $first,
    after: $after
    where: {
      language: $language
      orderby: {
        field: MENU_ORDER,
        order: ASC,
      },
    }
  ) {
    nodes {
      translation(language: $translation){
        date
        title
        slug
        customFields:investorCustomFields {
          pdfFile {
            node {
              mediaItemUrl
            }
          }
        }
      }
    }
    pageInfo {
      endCursor
      hasNextPage
      hasPreviousPage
      startCursor
    }
  }
}