query QueryYachtsWithSeries {
  yachtSeriesList(first: 99) {
    nodes {
      slug
      name
      yachtsSeriesCustomFields {
        seriesSimpleDescription
        seriesKeyImage {
          node {
            mediaItemUrl
          }
        }
      }
      yachts(
        first: 99,
        where: {
          orderby: {
            field: MENU_ORDER,
            order: ASC,
          }
        }
      ) {
        nodes {
          slug
          title
        }
      }
    }
  }
}