#import '../fragments/yacht.gql'

query QuerySingleYachtPage($slug:ID!, $yachtSlugForRelatedPost:String) {
  yacht(id:$slug, idType: SLUG) {
    ...yachtBasic
    yachtSeriesList {
      nodes {
        slug
        name
      }
    }
    yachtCustomFields {
      yachtDescription
      relatedPublicationSlug
      ...yachtHeroVideo
      ...yachtHeroImage
      ...yachtExteriorImages
      ...yachtInteriorImages
      ...yachtGeneralArrangementImages
      ...yachtVRPreview
      ...yachtVideosPreview
      ...yachtEmbedVideosGallery
      ...yachtSpecsTable
      ...yachtHulls
    }
  }
  posts(
    first: 3,
    where: {
      relatedYacht: $yachtSlugForRelatedPost,
      taxQuery: {
        relation: AND,
        taxArray: [
          {
            taxonomy: CATEGORY,
            field: SLUG,
            terms: ["uncategorized"]
            operator: NOT_IN,
          },
        ]
      }
  }) {
    nodes {
      slug
      title
      date
      categories {
        nodes {
          slug
          name
        }
      }
      postCustomFields {
        gallery {
          image {
            node {
              mediaItemUrl
            }
          }
        }
      }
    }
  }
}