query QueryYachtsWithSeries(
  $language: LanguageCodeFilterEnum
  $translation: LanguageCodeEnum!
) {
  yachtSeriesList(
    first: 99,
    where: {
      language: $language
    }
  ) {
    nodes {
      translation(language: $translation){
        slug
        name
        yachtsSeriesCustomFields {
          seriesSimpleDescription
          seriesKeyImage {
            node {
              mediaItemUrl
            }
          }
        }
        yachts(
          first: 99,
          where: {
            orderby: {
              field: MENU_ORDER,
              order: ASC,
            }
          }
        ) {
          nodes {
            slug
            title
          }
        }
      }
    }
  }
}