#import '../fragments/yacht.gql'

query QuerySingleSeriesPage($slug: ID!) {
  yachtSeries(id: $slug, idType: SLUG) {
    yachts(
      first: 99,
      where: {
        orderby: {
          field: MENU_ORDER,
          order: ASC,
        }
      }
    ){
      nodes {
        ...yachtBasic
        yachtCustomFields {
          ...yachtExteriorImages
          ...yachtSpecsTable
        }
      }
    }
  }
}
