#import '../fragments/yacht.gql'

query QuerySingleYachtPage(
  $slug: ID!,
  $yachtSlugForRelatedPost: String,
  # $language: LanguageCodeFilterEnum, # 20250426 新增需求：相關 news 只接英文版
  $translation: LanguageCodeEnum!
){
  yacht(
    id: $slug,
    idType: SLUG
  ){
    translation(language: $translation){
      ...yachtBasic
      yachtSeriesList {
        nodes {
          slug
          name
        }
      }
      yachtCustomFields {
        yachtDescription
        ...yachtHeroVideo
        ...yachtHeroImage
        ...yachtExteriorImages
        ...yachtInteriorImages
        ...yachtGeneralArrangementImages
        ...yachtVRPreview
        ...yachtVideosPreview
        ...yachtEmbedVideosGallery
        ...yachtSpecsTable
      }
    }
    EN:translation(language: EN){
      yachtCustomFields {
        ...yachtRelatedPublications
      }
    }
  }
  posts(
    first: 3,
    where: {
      language: EN # 20250426 新增需求：相關 news 只接英文版
      relatedYacht: $yachtSlugForRelatedPost,
      # 無論是否有分類皆撈取
      # taxQuery: {
      #   relation: AND,
      #   taxArray: [
      #     {
      #       taxonomy: CATEGORY,
      #       field: SLUG,
      #       terms: ["uncategorized"]
      #       operator: NOT_IN,
      #     },
      #   ]
      # }
  }) {
    nodes {
      slug
      title
      date
      categories {
        nodes {
          slug
          name
        }
      }
      postCustomFields {
        gallery {
          image {
            node {
              mediaItemUrl
              srcSet
            }
          }
        }
      }
    }
  }
}

query QuerySingleYachtHullsList(
  $slug: ID!
  # $translation: LanguageCodeEnum! # 20250426 新增需求：Hull 只接英文版
){
  yacht(
    id: $slug,
    idType: SLUG
  ){
    translation(
      language: EN # 20250426 新增需求：Hull 只接英文版
    ){
      yachtCustomFields {
        hulls {
          hullName
          isHidden
          vrEmbedUrl
        }
      }
    }
  }
}