#import '../fragments/yacht.gql'

query QuerySingleSeriesPage(
  $slug: ID!
  $translation: LanguageCodeEnum!
) {
  yachtSeries(
    id: $slug,
    idType: SLUG
  ){
    translation(
      language: $translation
    ){
      yachts(
        first: 99,
        where: {
          orderby: {
            field: MENU_ORDER,
            order: ASC,
          }
        }
      ){
        nodes {
          ...yachtBasic
          yachtCustomFields {
            ...yachtExteriorImages
            ...yachtSpecsTable
          }
        }
      }
    }
  }
}
