query QuerySinglePost($categorySlug: ID!, $postSlug: String) {
  category(id: $categorySlug, idType: SLUG) {
    id
    posts(where: {name: $postSlug}, first: 1) {
      nodes {
        title
        date
        content(format: RENDERED)
        categories(where: {parent: 0}, first: 1) {
          nodes {
            slug
            name
          }
        }
        postCustomFields {
            gallery {
              image {
                node {
                  mediaItemUrl
                }
              }
            }
          }
      }
      pageInfo {
        startCursor
        endCursor
        hasPreviousPage
        hasNextPage
      }
    }
  }
}

query QueryRelatedPosts($categorySlug:ID!, $after:String, $before:String, $first:Int, $last:Int) {
  category(id:$categorySlug, idType: SLUG) {
    id
    posts(
      after: $after
      before: $before
      first: $first
      last: $last
    ) {
      nodes {
        slug
        title
        date
        categories(where: {parent: 0}, first: 1) {
          nodes {
            slug
            name
          }
        }
        postCustomFields {
            gallery {
              image {
                node {
                  mediaItemUrl
                }
              }
            }
          }
      }
    }
  }
}
