#import '../fragments/post.gql'

query QueryPostsByCategory(
  $slug: ID!
  $first: Int
  $last: Int
  $after: String
  $before: String
  $relatedYachtSeries: String
  $year: Int
  $translation: LanguageCodeEnum!
) {
    category(id:$slug, idType: SLUG) {
      translation(language: $translation) {
        name
        posts(
          first: $first
          last: $last,
          after: $after,
          before: $before,
          where: {
            relatedYachtSeries: $relatedYachtSeries
            dateQuery: {
              year: $year
            }
          }
        ) {
          nodes {
            ...postBasic
            categories(
              first: 1,
              where: {
                parent: 0,
                orderby: TERM_ORDER,
                order: ASC,
              }
            ) {
              nodes {
                slug
                name
              }
            }
            postCustomFields {
              ...postCoverImage
              ...postGallery
              ...postRelatedYachts
            }
          }
          pageInfo {
            endCursor
            hasNextPage
            hasPreviousPage
            startCursor
          }
        }
      }
    }
}