#import '../fragments/post.gql'

query QueryNewsPage(
  $first: Int
  $last: Int
  $after: String
  $before: String
  $relatedYachtSeries: String
  $categories: [String]
  $year: Int
  $categoriesOperator: TaxQueryOperator = NOT_IN
) {
  posts(
    first: $first
 		last: $last,
    after: $after,
    before: $before,
    where: {
      language: EN #只接英文版
      dateQuery: {
        year: $year
      }
      taxQuery: {
        relation: AND,
        taxArray: [
          {
            taxonomy: CATEGORY,
            field: SLUG,
            terms: ["uncategorized", "cover-story"]
            operator: NOT_IN,
          },
          {
            taxonomy: CATEGORY,
            field: SLUG,
            terms: $categories,
            operator: $categoriesOperator,
          }
        ]
      }
      relatedYachtSeries: $relatedYachtSeries
    }
  ) {
    nodes {
      slug
      title
      date
      categories {
        nodes {
          slug
          name
          parentId
        }
      }
      postCustomFields {
        ...postGallery
        ...postRelatedYachts
      }
    }
    pageInfo {
      endCursor
      hasNextPage
      hasPreviousPage
      startCursor
    }
  }
  categories(
    first: 99,
    where: {
      language: EN #只接英文版
      orderby: TERM_ORDER,
      order: ASC,
    }
  ) {
    nodes {
      slug
      name
    }
  }
  coverStory:category(
    id: "cover-story",
    idType: SLUG
  ){
    translation(
      language: EN #只接英文版
    ){
      posts(first: 1) {
        nodes {
          slug
          title
          date
          postCustomFields {
            ...postCoverImage
          }
        }
      }
    }
  }
  events:category(
    id: "events",
    idType: SLUG
  ){
    translation(
      language: EN #只接英文版
    ){
      posts(first: 3) {
        nodes {
          slug
          title
          date
          postCustomFields {
            ...postGallery
          }
        }
      }
    }
  }
  publicationCategory(id: "brand-publication", idType: SLUG) {
    publications(
      first: 1,
      where: {
        orderby: {
          field: MENU_ORDER,
          order: ASC
        }
      }
    ) {
      nodes {
        translation(
          language: EN #只接英文版
        ){
          publicationCustomFields {
            publication {
              publicationCover {
                node {
                  mediaItemUrl
                  srcSet
                }
              }
              pdf {
                node {
                  mediaItemUrl
                }
              }
            }
          }
        }
      }
    }
  }
  newsPageSettings(
    language: EN #只接英文版
  ) {
    ownerPerspective {
      description
      image {
        node {
          mediaItemUrl
          srcSet
        }
      }
    }
  }
}