query QuerySinglePost(
  $categorySlug: ID!,
  $postSlug: String,
) {
  category(
    id: $categorySlug,
    idType: SLUG
  ) {
    id
    posts(
      first: 1,
      where: {
        name: $postSlug,
      },
    ){
      nodes {
        title
        date
        content(format: RENDERED)
        categories(
          first: 1
          where: {
            parent: 0,
            orderby: TERM_ORDER,
            order: ASC,
          },
        ) {
          nodes {
            slug
            name
          }
        }
        postCustomFields {
            gallery {
              image {
                node {
                  mediaItemUrl
                  srcSet
            }
          }
        }
      }
      pageInfo {
        startCursor
        endCursor
        hasPreviousPage
        hasNextPage
      }
    }
  }
}

query QueryRelatedPosts(
  $categorySlug:ID!,
  $after:String,
  $before:String,
  $first:Int,
  $last:Int
) {
  category(
    id:$categorySlug,
    idType: SLUG
  ) {
    id
    posts(
      after: $after
      before: $before
      first: $first
      last: $last
    ) {
      nodes {
        slug
        title
        date
        categories(
          first: 1
          where: {
            parent: 0
            orderby: TERM_ORDER,
            order: ASC,
          },
        ) {
          nodes {
            slug
            name
          }
        }
        postCustomFields {
            gallery {
              image {
                node {
                  mediaItemUrl
                  srcSet
                }
              }
            }
          }
      }
    }
  }
}
