query QueryPolicyPage {
  globalSettings {
    additionalContent {
      privacyPolicy {
        content
      }
      termsAndConditions {
        content
      }
      qaList {
        question
        answer
      }
    }
  }
}