query QueryPolicyPage(
  $language: LanguageCodeFilterEnum
){
  globalSettings(
    language: $language
  ){
    additionalContent {
      privacyPolicy {
        content
      }
      termsAndConditions {
        content
      }
      qaList {
        question
        answer
      }
    }
  }
}