query QueryPublicationsPage(
	$language: LanguageCodeFilterEnum = EN,
) {
  publicationCategories(where: {language: $language}) {
    nodes {
      slug
      name
      publications(
        first: 6,
        where: {
          orderby: {
            field: MENU_ORDER,
            order: ASC
          }
        }
      ) {
        nodes {
          slug
          title
          publicationCustomFields {
            publication {
              publicationCover {
                node {
                  mediaItemUrl
                }
              }
              pdf {
                node {
                  mediaItemUrl
                }
              }
            }
          }
        }
      }
    }
  }
}