query QueryPublicationsPage(
	$language: LanguageCodeFilterEnum = EN,
) {
  publicationCategories(where: {language: $language}) {
    nodes {
      slug
      name
      publications(first: 6) {
        nodes {
          slug
          title
          publicationCustomFields {
            publication {
              publicationCover {
                node {
                  mediaItemUrl
                }
              }
              pdf {
                node {
                  mediaItemUrl
                }
              }
            }
          }
        }
      }
    }
  }
}