query QueryTeamPage(
  $language: LanguageCodeFilterEnum
) {
  teamPageSettings(
    language: $language
  ){
    teamPageCustomFields {
      pageTitle
      teamIntroduction
      teamMembers {
        name
        subtitle
        contactEmail
        image {
          node {
            mediaItemUrl
            srcSet
          }
        }
      }
    }
  }
}