query QueryTeamPage(
  $language: LanguageCodeFilterEnum = EN
) {
  teamPageSettings(
    language: $language
  ){
    teamPageCustomFields {
      pageTitle
      teamIntroduction
      teamMembers {
        name
        subtitle
        contactEmail
        image {
          node {
            mediaItemUrl
          }
        }
      }
    }
  }
}