query QueryTeamPage {
  teamPageSettings {
    teamPageCustomFields {
      pageTitle
      teamIntroduction
      teamMembers {
        name
        subtitle
        contactEmail
        image {
          node {
            mediaItemUrl
          }
        }
      }
    }
  }
}