fragment postBasic on Post {
  slug
  title
  date
  content(format: RENDERED)
}

fragment postCoverImage on PostCustomFields {
  coverImage {
    node {
      mediaItemUrl
      srcSet
    }
  }
}

fragment postGallery on PostCustomFields {
  gallery {
    image {
      node {
        mediaItemUrl
        srcSet
      }
    }
  }
}

fragment postRelatedYachts on PostCustomFields {
  relatedYachts {
    nodes {
      ... on Yacht {
        slug
        title
        databaseId
        yachtSeriesList(first: 1) {
          nodes {
            name
            slug
          }
        }
      }
    }
  }
}