#import '../fragments/hull.gql'

fragment yachtBasic on Yacht {
  slug
  title
}

fragment yachtExcludeDealers on YachtCustomFields {
  excludeDealers
}

fragment yachtHeroVideo on YachtCustomFields {
  heroVideo {
    node {
      mediaItemUrl
    }
  }
}

fragment yachtHeroImage on YachtCustomFields {
  heroImage {
    node {
      mediaItemUrl
      srcSet
    }
  }
}

fragment yachtExteriorImages on YachtCustomFields {
  exteriorImages {
    image {
      node {
        mediaItemUrl
        srcSet
      }
    }
  }
}

fragment yachtInteriorImages on YachtCustomFields {
  interiorImages {
    image {
      node {
        mediaItemUrl
        srcSet
      }
    }
    description
  }
}

fragment yachtGeneralArrangementImages on YachtCustomFields {
  generalArrangementImages {
    type
    images {
      title
      image {
        node {
          mediaItemUrl
          srcSet
        }
      }
    }
  }
}

fragment yachtVRPreview on YachtCustomFields {
   vrPreview {
    previewVideo {
      node {
        mediaItemUrl
      }
    }
    previewImage {
      node {
        mediaItemUrl
        srcSet
      }
    }
  }
}

fragment yachtVideosPreview on YachtCustomFields {
  videosPreview {
    previewVideo {
      node {
        mediaItemUrl
      }
    }
    previewImage {
      node {
        mediaItemUrl
        srcSet
      }
    }
  }
}

fragment yachtEmbedVideosGallery on YachtCustomFields {
  embedVideosGallery {
    embedUrl
  }
}

fragment yachtRelatedPublications on YachtCustomFields {
  relatedPublication {
    nodes {
      ... on Publication {
        title
        publicationCustomFields {
          publication {
            publicationCover {
              node {
                mediaItemUrl
                srcSet
              }
            }
            pdf {
              node {
                mediaItemUrl
              }
            }
          }
        }
      }
    }
  }
}

fragment yachtSpecTerms on YachtCustomFieldsSpecsTableSpecTerms {
  loa {
    metric
    imperial
  }
  lwl {
    metric
    imperial
  }
  beam {
    metric
    imperial
  }
  draft {
    metric
    imperial
  }
  engines {
    metric
    imperial
  }
  generator {
    metric
    imperial
  }
  displacement {
    metric
    imperial
  }
  fuelCapacity {
    metric
    imperial
  }
  waterCapacity {
    metric
    imperial
  }
  cabins {
    metric
    imperial
  }
}

fragment yachtSpecsTable on YachtCustomFields {
  specsTable {
    specType
    specTerms{
      ...yachtSpecTerms
    }
  }
}

fragment yachtHulls on YachtCustomFields {
  hulls {
    hullName
    vrEmbedUrl
    ...hullExteriorImages
    ...hullInteriorImages
    ...hullGeneralArrangementImages
    ...hullEmbedVideosGallery
    specTerms {
      ...hullSpecTerms
    }
  }
}